### PR TITLE
 Open up the nestedScrollEnabled prop

### PR DESCRIPTION
**Pull request by mheddomagic**
Open up the nestedScrollEnabled prop to prevent needing a patch like suggested [here](https://github.com/YanYuanFE/react-native-signature-canvas/issues/112#issuecomment-1671071178) or [here](https://github.com/YanYuanFE/react-native-signature-canvas/issues/333) 

I am using the signature screen inside a [bottom sheet](https://github.com/gorhom/react-native-bottom-sheet) and enabling this prop to true stops the android 'dots only' issue. Can we allow devs to use this prop if it helps?

### CODE REVIEW

**Comment by mheddomagic** [comment]
@YanYuanFE ?

**Comment by YanYuanFE** [comment]
thanks

**Comment by mheddomagic** [comment]
@YanYuanFE Do you happen to know when this change will be released?

**Comment by YanYuanFE** [comment]
4.7.2 released

**Pull request merged**
