### PR TITLE
Implementing a way to send the signature data when ending the drawing

### PR DESCRIPTION
**Pull request by riamon-v**
Hello !

I know it is not perfect but I tried to allow the user to access the data from the signature when ending the drawing. I'd love to see these changing coming in the future for this plugin so here is my version (not very impressive but at least doing the trick !)

### CODE REVIEW

**Comment by YanYuanFE** [comment]
I think this kind of realization is not necessary, If you want to get the signature after onEnd event, you can use **readSignature** in the **onEnd** event. you can see this example, Thanks.

https://github.com/YanYuanFE/react-native-signature-canvas/blob/master/example/expo-app/App.js

**Comment by YanYuanFE** [comment]
readSignature can manually get the signature, and then get the signature data in the onOk event.

**Comment by riamon-v** [comment]
> readSignature can manually get the signature, and then get the signature data in the onOk event.

I actually saw the readSignature function but it can't match my use as I instanciate severals Signatures in the same page. Then readSignature only get the signature of one of the refs

**Comment by riamon-v** [comment]
> readSignature can manually get the signature, and then get the signature data in the onOk event.

I still need this feature as I instanciate severals signature in the same page. I tried your solution with readSignature before but it doesn't match the intended behaviour

**Comment by YanYuanFE** [comment]
OK, I find a problem of readSignature when use multiple Signature, I try to fix it.

**Comment by YanYuanFE** [comment]
I has been release v2.6.0, support multiple Signature component,you can see this example:
https://github.com/YanYuanFE/react-native-signature-canvas/blob/master/example/expo-app/App.js

**Pull request closed without merging**
